kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongoexpress
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress
          image: localhost:5000/mongoexpress
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_DATABASE
              value: mongo
            - name: MONGO_HOST
              value: mongo-nodeport-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: adminuser
            - name: MONGO_PASSWORD
              value: password123
      restartPolicy: Always
