apiVersion: v1
kind: Service
metadata:
  labels:
    app: project-mongodb
  name: project-mongo-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: project-mongodb