kind: Service
apiVersion: v1
metadata:
  name: mongoexpress
spec:
  type: NodePort
  #type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      nodePort: 31001
  selector:
    app: mongoexpress