apiVersion: v1
kind: ConfigMap
metadata:
  name: server-side-configs
data:
  PORT: "5000"
  CLIENT: <front-end-app-service-ip>:<port>
  MONGODB_URL: mongodb://project-mongo-db-service:27017/project-k8s