const VOICEACTOR__GET_LIST = 'VOICEACTOR__GET_LIST';
const VOICEACTOR_CREATE = 'VOICEACTOR_CREATE'
const VOICEACTOR_EDIT = 'VOICEACTOR_EDIT'
const VOICEACTOR_DELETE = 'VOICEACTOR_DELETE'

const types = {
    VOICEACTOR__GET_LIST,
    VOICEACTOR_CREATE,
    VOICEACTOR_EDIT,
    VOICEACTOR_DELETE
};

export default types;